-- PilotBank v11.60.0 — Push notifications + Announcements + Weekly Ranking
-- Safe additive migration. Existing study-group data is not removed.
-- Run after the existing member/profile/learning schema. Re-runnable.

begin;

create extension if not exists pgcrypto;

create or replace function public.pilotbank_is_approved(p_user_id uuid default auth.uid())
returns boolean language sql stable security definer set search_path=public,pg_temp as $$
  select exists(select 1 from public.profiles p where p.id=p_user_id and p.approval_status='approved');
$$;
create or replace function public.pilotbank_is_admin(p_user_id uuid default auth.uid())
returns boolean language sql stable security definer set search_path=public,pg_temp as $$
  select exists(select 1 from public.profiles p where p.id=p_user_id and p.approval_status='approved' and coalesce(p.is_admin,false));
$$;
create or replace function public.pilotbank_current_week_start()
returns date language sql stable as $$
  select ((now() at time zone 'Asia/Seoul')::date - (extract(isodow from (now() at time zone 'Asia/Seoul'))::int - 1));
$$;

create table if not exists public.app_public_settings(
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);
insert into public.app_public_settings(key,value,updated_at)
values ('push_vapid_public_key','BNpAmVlSJAXlbK-Y1d8sbNQwxk0aT-rqo3f8patlwF9QJ2Kwou92Y323RJTMelciHrzbQm_qR5smvZ0poDK2or0',now())
on conflict(key) do update set value=excluded.value, updated_at=excluded.updated_at;

create table if not exists public.push_subscriptions(
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth_key text not null,
  user_agent text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists push_subscriptions_user_idx on public.push_subscriptions(user_id,updated_at desc);

create table if not exists public.user_activity(
  user_id uuid primary key references auth.users(id) on delete cascade,
  last_seen_at timestamptz not null default now(),
  last_inactivity_notified_for_seen_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.announcements(
  id uuid primary key default gen_random_uuid(),
  title text not null check(char_length(btrim(title)) between 2 and 120),
  body text not null check(char_length(btrim(body)) between 2 and 4000),
  created_by uuid not null references auth.users(id) on delete cascade,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  push_sent_at timestamptz
);
create index if not exists announcements_created_idx on public.announcements(created_at desc);

create table if not exists public.push_delivery_log(
  id bigint generated by default as identity primary key,
  subscription_id uuid references public.push_subscriptions(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  event_key text not null,
  status text not null default 'sent',
  created_at timestamptz not null default now(),
  unique(subscription_id,event_key)
);

create table if not exists public.weekly_ranking_rounds(
  id uuid primary key default gen_random_uuid(),
  week_start date not null unique,
  week_end date not null,
  title text not null,
  duration_minutes integer not null default 50 check(duration_minutes between 1 and 180),
  question_count integer not null default 50 check(question_count between 1 and 100),
  question_ids text[] not null,
  pool_version text not null default 'weekly-text-v1',
  created_at timestamptz not null default now()
);

create table if not exists public.weekly_ranking_entries(
  id uuid primary key default gen_random_uuid(),
  round_id uuid not null references public.weekly_ranking_rounds(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'started' check(status in ('started','submitted')),
  started_at timestamptz not null default now(),
  submitted_at timestamptz,
  score integer,
  duration_seconds integer,
  answers jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(round_id,user_id)
);
create index if not exists weekly_ranking_entries_rank_idx on public.weekly_ranking_entries(round_id,status,score desc,duration_seconds asc,submitted_at asc);

create table if not exists public.weekly_ranking_comments(
  id uuid primary key default gen_random_uuid(),
  round_id uuid not null references public.weekly_ranking_rounds(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  body text not null check(char_length(btrim(body)) between 1 and 1000),
  created_at timestamptz not null default now()
);
create index if not exists weekly_ranking_comments_round_idx on public.weekly_ranking_comments(round_id,created_at asc);

-- RLS / grants
alter table public.app_public_settings enable row level security;
alter table public.push_subscriptions enable row level security;
alter table public.user_activity enable row level security;
alter table public.announcements enable row level security;
alter table public.push_delivery_log enable row level security;
alter table public.weekly_ranking_rounds enable row level security;
alter table public.weekly_ranking_entries enable row level security;
alter table public.weekly_ranking_comments enable row level security;

revoke all on public.app_public_settings,public.push_subscriptions,public.user_activity,public.announcements,public.push_delivery_log,public.weekly_ranking_rounds,public.weekly_ranking_entries,public.weekly_ranking_comments from anon,authenticated;
grant select on public.app_public_settings to authenticated;
grant select,insert,update,delete on public.push_subscriptions to authenticated;
grant select,insert,update on public.user_activity to authenticated;
grant select,insert,update,delete on public.announcements to authenticated;

drop policy if exists app_public_settings_read on public.app_public_settings;
create policy app_public_settings_read on public.app_public_settings for select to authenticated using(public.pilotbank_is_approved(auth.uid()));

drop policy if exists push_subscriptions_own_select on public.push_subscriptions;
create policy push_subscriptions_own_select on public.push_subscriptions for select to authenticated using(user_id=auth.uid());
drop policy if exists push_subscriptions_own_insert on public.push_subscriptions;
create policy push_subscriptions_own_insert on public.push_subscriptions for insert to authenticated with check(user_id=auth.uid() and public.pilotbank_is_approved(auth.uid()));
drop policy if exists push_subscriptions_own_update on public.push_subscriptions;
create policy push_subscriptions_own_update on public.push_subscriptions for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
drop policy if exists push_subscriptions_own_delete on public.push_subscriptions;
create policy push_subscriptions_own_delete on public.push_subscriptions for delete to authenticated using(user_id=auth.uid());

drop policy if exists user_activity_own_select on public.user_activity;
create policy user_activity_own_select on public.user_activity for select to authenticated using(user_id=auth.uid());
drop policy if exists user_activity_own_insert on public.user_activity;
create policy user_activity_own_insert on public.user_activity for insert to authenticated with check(user_id=auth.uid() and public.pilotbank_is_approved(auth.uid()));
drop policy if exists user_activity_own_update on public.user_activity;
create policy user_activity_own_update on public.user_activity for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());

drop policy if exists announcements_read on public.announcements;
create policy announcements_read on public.announcements for select to authenticated using(is_published and public.pilotbank_is_approved(auth.uid()));
drop policy if exists announcements_admin_insert on public.announcements;
create policy announcements_admin_insert on public.announcements for insert to authenticated with check(public.pilotbank_is_admin(auth.uid()) and created_by=auth.uid());
drop policy if exists announcements_admin_update on public.announcements;
create policy announcements_admin_update on public.announcements for update to authenticated using(public.pilotbank_is_admin(auth.uid())) with check(public.pilotbank_is_admin(auth.uid()));
drop policy if exists announcements_admin_delete on public.announcements;
create policy announcements_admin_delete on public.announcements for delete to authenticated using(public.pilotbank_is_admin(auth.uid()));

-- Round list hides question IDs until the user actually starts.
create or replace function public.weekly_ranking_round_list(p_limit integer default 12)
returns table(round_id uuid,week_start date,week_end date,title text,duration_minutes integer,question_count integer,created_at timestamptz,my_status text,my_score integer,my_duration_seconds integer)
language sql stable security definer set search_path=public,pg_temp as $$
  select r.id,r.week_start,r.week_end,r.title,r.duration_minutes,r.question_count,r.created_at,
         e.status,e.score,e.duration_seconds
  from public.weekly_ranking_rounds r
  left join public.weekly_ranking_entries e on e.round_id=r.id and e.user_id=auth.uid()
  where public.pilotbank_is_approved(auth.uid())
  order by r.week_start desc
  limit greatest(1,least(coalesce(p_limit,12),52));
$$;

create or replace function public.weekly_ranking_start(p_round_id uuid)
returns jsonb language plpgsql volatile security definer set search_path=public,pg_temp as $$
declare r public.weekly_ranking_rounds%rowtype; e public.weekly_ranking_entries%rowtype; deadline timestamptz;
begin
  if not public.pilotbank_is_approved(auth.uid()) then raise exception 'Approved members only'; end if;
  select * into r from public.weekly_ranking_rounds where id=p_round_id;
  if not found then raise exception 'Ranking round not found'; end if;
  if r.week_start<>public.pilotbank_current_week_start() then
    select * into e from public.weekly_ranking_entries where round_id=r.id and user_id=auth.uid();
    if not found then raise exception 'Past ranking rounds cannot be started'; end if;
  else
    insert into public.weekly_ranking_entries(round_id,user_id,status,started_at)
    values(r.id,auth.uid(),'started',now()) on conflict(round_id,user_id) do nothing;
    select * into e from public.weekly_ranking_entries where round_id=r.id and user_id=auth.uid();
  end if;
  deadline:=e.started_at+make_interval(mins=>r.duration_minutes);
  return jsonb_build_object('round_id',r.id,'title',r.title,'week_start',r.week_start,'status',e.status,'started_at',e.started_at,'deadline_at',deadline,'duration_minutes',r.duration_minutes,'question_count',r.question_count,'question_ids',to_jsonb(r.question_ids),'score',e.score,'duration_seconds',e.duration_seconds,'submitted_at',e.submitted_at,'answers',e.answers);
end;$$;

create or replace function public.weekly_ranking_save_draft(p_round_id uuid,p_answers jsonb)
returns void language plpgsql volatile security definer set search_path=public,pg_temp as $$
declare e public.weekly_ranking_entries%rowtype; r public.weekly_ranking_rounds%rowtype; k text; v text; clean jsonb='{}'::jsonb;
begin
  if not public.pilotbank_is_approved(auth.uid()) then raise exception 'Approved members only'; end if;
  select * into e from public.weekly_ranking_entries where round_id=p_round_id and user_id=auth.uid() for update;
  if not found or e.status<>'started' then return; end if;
  select * into r from public.weekly_ranking_rounds where id=p_round_id;
  if now()>e.started_at+make_interval(mins=>r.duration_minutes)+interval '10 seconds' then return; end if;
  for k,v in select key,value#>>'{}' from jsonb_each(coalesce(p_answers,'{}'::jsonb)) loop
    if k=any(r.question_ids) and upper(v) in ('A','B','C','D') then clean:=clean||jsonb_build_object(k,upper(v)); end if;
  end loop;
  update public.weekly_ranking_entries set answers=coalesce(answers,'{}'::jsonb)||clean,updated_at=now() where id=e.id;
end;$$;

create or replace function public.weekly_ranking_my_entry(p_round_id uuid)
returns jsonb language sql stable security definer set search_path=public,pg_temp as $$
  select case when not public.pilotbank_is_approved(auth.uid()) then null else (
    select jsonb_build_object('round_id',e.round_id,'status',e.status,'started_at',e.started_at,'submitted_at',e.submitted_at,'score',e.score,'duration_seconds',e.duration_seconds,'answers',e.answers)
    from public.weekly_ranking_entries e where e.round_id=p_round_id and e.user_id=auth.uid()
  ) end;
$$;

create or replace function public.weekly_ranking_leaderboard(p_round_id uuid)
returns table(rank_no bigint,user_id uuid,display_name text,score integer,duration_seconds integer,submitted_at timestamptz,is_me boolean)
language plpgsql stable security definer set search_path=public,pg_temp as $$
begin
  if not public.pilotbank_is_admin(auth.uid()) and not exists(select 1 from public.weekly_ranking_entries e where e.round_id=p_round_id and e.user_id=auth.uid() and e.status='submitted') then
    raise exception 'Submit this ranking round before viewing the leaderboard';
  end if;
  return query
  select row_number() over(order by e.score desc,e.duration_seconds asc,e.submitted_at asc)::bigint,
         e.user_id,coalesce(nullif(btrim(p.username),''),split_part(coalesce(p.email,''),'@',1),'회원')::text,
         e.score,e.duration_seconds,e.submitted_at,(e.user_id=auth.uid())
  from public.weekly_ranking_entries e left join public.profiles p on p.id=e.user_id
  where e.round_id=p_round_id and e.status='submitted'
  order by e.score desc,e.duration_seconds asc,e.submitted_at asc;
end;$$;

create or replace function public.weekly_ranking_comments_list(p_round_id uuid)
returns table(comment_id uuid,user_id uuid,display_name text,body text,created_at timestamptz,can_delete boolean)
language plpgsql stable security definer set search_path=public,pg_temp as $$
begin
  if not public.pilotbank_is_admin(auth.uid()) and not exists(select 1 from public.weekly_ranking_entries e where e.round_id=p_round_id and e.user_id=auth.uid() and e.status='submitted') then raise exception 'Submit before viewing comments'; end if;
  return query select c.id,c.user_id,coalesce(nullif(btrim(p.username),''),split_part(coalesce(p.email,''),'@',1),'회원')::text,c.body,c.created_at,(c.user_id=auth.uid() or public.pilotbank_is_admin(auth.uid()))
  from public.weekly_ranking_comments c left join public.profiles p on p.id=c.user_id where c.round_id=p_round_id order by c.created_at asc;
end;$$;

create or replace function public.weekly_ranking_post_comment(p_round_id uuid,p_body text)
returns uuid language plpgsql volatile security definer set search_path=public,pg_temp as $$
declare cid uuid;
begin
  if char_length(btrim(coalesce(p_body,''))) not between 1 and 1000 then raise exception 'Comment must be 1-1000 characters'; end if;
  if not public.pilotbank_is_admin(auth.uid()) and not exists(select 1 from public.weekly_ranking_entries e where e.round_id=p_round_id and e.user_id=auth.uid() and e.status='submitted') then raise exception 'Submit before commenting'; end if;
  insert into public.weekly_ranking_comments(round_id,user_id,body) values(p_round_id,auth.uid(),btrim(p_body)) returning id into cid; return cid;
end;$$;

create or replace function public.weekly_ranking_delete_comment(p_comment_id uuid)
returns void language plpgsql volatile security definer set search_path=public,pg_temp as $$
begin
  delete from public.weekly_ranking_comments c where c.id=p_comment_id and (c.user_id=auth.uid() or public.pilotbank_is_admin(auth.uid()));
end;$$;

revoke all on function public.pilotbank_is_approved(uuid),public.pilotbank_is_admin(uuid) from public,anon;
grant execute on function public.pilotbank_is_approved(uuid),public.pilotbank_is_admin(uuid) to authenticated;
revoke all on function public.weekly_ranking_round_list(integer),public.weekly_ranking_start(uuid),public.weekly_ranking_save_draft(uuid,jsonb),public.weekly_ranking_my_entry(uuid),public.weekly_ranking_leaderboard(uuid),public.weekly_ranking_comments_list(uuid),public.weekly_ranking_post_comment(uuid,text),public.weekly_ranking_delete_comment(uuid) from public,anon;
grant execute on function public.weekly_ranking_round_list(integer),public.weekly_ranking_start(uuid),public.weekly_ranking_save_draft(uuid,jsonb),public.weekly_ranking_my_entry(uuid),public.weekly_ranking_leaderboard(uuid),public.weekly_ranking_comments_list(uuid),public.weekly_ranking_post_comment(uuid,text),public.weekly_ranking_delete_comment(uuid) to authenticated;

commit;
notify pgrst,'reload schema';
