-- Aviation Question Bank v11.39
-- Supabase learning data tables + RLS
-- Run once in Supabase SQL Editor before deploying the v11.39 web patch.

-- Re-create the administrator helper used by RLS (safe to re-run).
create schema if not exists private;
create or replace function private.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles
    where id = (select auth.uid())
      and is_admin = true
  );
$$;
grant usage on schema private to authenticated;
grant execute on function private.is_admin() to authenticated;

-- 1) Aggregated per-question progress used by the learner UI/statistics.
create table if not exists public.user_question_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id text not null,
  subject text,
  study_unit text,
  subunit text,
  attempts integer not null default 0 check (attempts >= 0),
  correct integer not null default 0 check (correct >= 0),
  incorrect integer not null default 0 check (incorrect >= 0),
  last_result text check (last_result in ('correct','incorrect') or last_result is null),
  last_answer text,
  last_attempted timestamptz,
  error_reported boolean not null default false,
  error_reported_at timestamptz,
  error_note text not null default '',
  error_question_snapshot text not null default '',
  error_choices_snapshot jsonb not null default '[]'::jsonb,
  error_subject_snapshot text not null default '',
  error_unit_snapshot text not null default '',
  error_subunit_snapshot text not null default '',
  updated_at timestamptz not null default now(),
  primary key (user_id, question_id)
);

-- 2) Favorites and exam-exclusion flags.
create table if not exists public.user_question_flags (
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id text not null,
  favorite boolean not null default false,
  exam_excluded boolean not null default false,
  updated_at timestamptz not null default now(),
  primary key (user_id, question_id)
);

-- 3) Append-only answer history for administrator/user history views.
create table if not exists public.user_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id text not null,
  selected_answer text,
  is_correct boolean not null,
  mode text,
  session_type text,
  subject text,
  study_unit text,
  subunit text,
  answered_at timestamptz not null default now()
);

create index if not exists user_attempts_user_time_idx
  on public.user_attempts (user_id, answered_at desc);
create index if not exists user_attempts_user_question_idx
  on public.user_attempts (user_id, question_id);
create index if not exists user_attempts_subject_idx
  on public.user_attempts (subject, study_unit);

-- 4) Theory-stage progress.
create table if not exists public.user_theory_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  storage_key text not null,
  stage_id text not null,
  read boolean not null default false,
  passed boolean not null default false,
  attempts integer not null default 0 check (attempts >= 0),
  best_score integer not null default 0 check (best_score >= 0),
  last_score integer,
  last_taken_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (user_id, storage_key, stage_id)
);

-- 5) Completed study/exam session summaries.
create table if not exists public.user_exam_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  session_type text,
  mode text,
  context_label text,
  question_count integer not null default 0 check (question_count >= 0),
  correct_count integer not null default 0 check (correct_count >= 0),
  score_pct integer check (score_pct between 0 and 100),
  question_ids jsonb not null default '[]'::jsonb,
  wrong_question_ids jsonb not null default '[]'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  completed_at timestamptz not null default now()
);

create index if not exists user_exam_sessions_user_time_idx
  on public.user_exam_sessions (user_id, completed_at desc);

-- Explicit RLS even when project-level automatic RLS is enabled.
alter table public.user_question_progress enable row level security;
alter table public.user_question_flags enable row level security;
alter table public.user_attempts enable row level security;
alter table public.user_theory_progress enable row level security;
alter table public.user_exam_sessions enable row level security;

-- Data API privileges. RLS below remains the actual row-level gate.
grant select, insert, update, delete on public.user_question_progress to authenticated;
grant select, insert, update, delete on public.user_question_flags to authenticated;
grant select, insert, delete on public.user_attempts to authenticated;
grant select, insert, update, delete on public.user_theory_progress to authenticated;
grant select, insert, delete on public.user_exam_sessions to authenticated;
grant usage, select on sequence public.user_attempts_id_seq to authenticated;

-- Drop only v11.39 policy names so the script can safely be re-run.
drop policy if exists "v1139 own question progress" on public.user_question_progress;
drop policy if exists "v1139 admin read question progress" on public.user_question_progress;
drop policy if exists "v1139 own question flags" on public.user_question_flags;
drop policy if exists "v1139 admin read question flags" on public.user_question_flags;
drop policy if exists "v1139 own attempts" on public.user_attempts;
drop policy if exists "v1139 admin read attempts" on public.user_attempts;
drop policy if exists "v1139 own theory progress" on public.user_theory_progress;
drop policy if exists "v1139 admin read theory progress" on public.user_theory_progress;
drop policy if exists "v1139 own exam sessions" on public.user_exam_sessions;
drop policy if exists "v1139 admin read exam sessions" on public.user_exam_sessions;

-- A signed-in user can read/write/delete only rows carrying their own auth.uid().
create policy "v1139 own question progress"
on public.user_question_progress
for all to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "v1139 own question flags"
on public.user_question_flags
for all to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "v1139 own attempts"
on public.user_attempts
for all to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "v1139 own theory progress"
on public.user_theory_progress
for all to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "v1139 own exam sessions"
on public.user_exam_sessions
for all to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

-- Administrator can read every learner's history. private.is_admin() was created in the previous setup step.
create policy "v1139 admin read question progress"
on public.user_question_progress
for select to authenticated
using ((select private.is_admin()));

create policy "v1139 admin read question flags"
on public.user_question_flags
for select to authenticated
using ((select private.is_admin()));

create policy "v1139 admin read attempts"
on public.user_attempts
for select to authenticated
using ((select private.is_admin()));

create policy "v1139 admin read theory progress"
on public.user_theory_progress
for select to authenticated
using ((select private.is_admin()));

create policy "v1139 admin read exam sessions"
on public.user_exam_sessions
for select to authenticated
using ((select private.is_admin()));
