import { createClient } from "npm:@supabase/supabase-js@2.57.4";
import webpush from "npm:web-push@3.6.7";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,x-client-info,apikey,content-type,x-cron-secret","Access-Control-Allow-Methods":"POST,OPTIONS"};
const url=Deno.env.get("SUPABASE_URL")!;const service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;const anon=Deno.env.get("SUPABASE_ANON_KEY")!;const cronSecret=Deno.env.get("CRON_SECRET")||"";
const vapidPublic=Deno.env.get("VAPID_PUBLIC_KEY")!;const vapidPrivate=Deno.env.get("VAPID_PRIVATE_KEY")!;const vapidSubject=Deno.env.get("VAPID_SUBJECT")||"mailto:pilotbank@example.com";
webpush.setVapidDetails(vapidSubject,vapidPublic,vapidPrivate);const admin=createClient(url,service,{auth:{persistSession:false}});
function json(data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:{...cors,"Content-Type":"application/json"}})}
async function caller(req:Request){const h=req.headers.get("Authorization")||"";if(!h.startsWith("Bearer "))return null;const c=createClient(url,anon,{global:{headers:{Authorization:h}},auth:{persistSession:false}});const {data}=await c.auth.getUser();return data.user||null}
async function profile(uid:string){const {data}=await admin.from("profiles").select("id,approval_status,is_admin").eq("id",uid).maybeSingle();return data}
async function sendOne(sub:any,payload:any,eventKey:string){const prior=await admin.from("push_delivery_log").select("id").eq("subscription_id",sub.id).eq("event_key",eventKey).maybeSingle();if(prior.data)return {skipped:true};try{await webpush.sendNotification({endpoint:sub.endpoint,keys:{p256dh:sub.p256dh,auth:sub.auth_key}},JSON.stringify(payload),{TTL:86400});await admin.from("push_delivery_log").insert({subscription_id:sub.id,user_id:sub.user_id,event_key:eventKey,status:"sent"});return {sent:true}}catch(e:any){const code=e?.statusCode||e?.status;if(code===404||code===410){await admin.from("push_subscriptions").delete().eq("id",sub.id)}else console.error("push",sub.id,e);return {error:String(e?.message||e)}}}
async function sendAnnouncement(a:any){const {data:subs,error}=await admin.from("push_subscriptions").select("id,user_id,endpoint,p256dh,auth_key");if(error)throw error;let sent=0;for(const sub of subs||[]){const p=await profile(sub.user_id);if(p?.approval_status!=="approved")continue;const r=await sendOne(sub,{title:`공지 · ${a.title}`,body:a.body,url:"./?open=announcements",tag:`announcement-${a.id}`},`announcement:${a.id}`);if(r.sent)sent++}await admin.from("announcements").update({push_sent_at:new Date().toISOString()}).eq("id",a.id);return sent}
async function processAnnouncements(){const {data,error}=await admin.from("announcements").select("*").eq("is_published",true).is("push_sent_at",null).gte("created_at",new Date(Date.now()-7*86400000).toISOString()).order("created_at");if(error)throw error;let total=0;for(const a of data||[])total+=await sendAnnouncement(a);return total}
async function processInactive(){const cutoff=new Date(Date.now()-24*3600000).toISOString();const {data:acts,error}=await admin.from("user_activity").select("user_id,last_seen_at,last_inactivity_notified_for_seen_at").lt("last_seen_at",cutoff);if(error)throw error;let users=0,sent=0;for(const a of acts||[]){if(a.last_inactivity_notified_for_seen_at&&new Date(a.last_inactivity_notified_for_seen_at).getTime()>=new Date(a.last_seen_at).getTime())continue;const p=await profile(a.user_id);if(p?.approval_status!=="approved")continue;const {data:subs}=await admin.from("push_subscriptions").select("id,user_id,endpoint,p256dh,auth_key").eq("user_id",a.user_id);if(!subs?.length)continue;users++;let any=false;for(const sub of subs){const key=`inactive:${a.user_id}:${a.last_seen_at}`;const r=await sendOne(sub,{title:"PilotBank 학습 알림",body:"학습을 멈춘지 하루가 지났습니다. 빨리 접속해서 학습을 재개하세요",url:"./",tag:"pilotbank-inactivity"},key);if(r.sent){sent++;any=true}}if(any)await admin.from("user_activity").update({last_inactivity_notified_for_seen_at:a.last_seen_at,updated_at:new Date().toISOString()}).eq("user_id",a.user_id)}return {users,sent}}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{const body=await req.json().catch(()=>({}));const isCron=cronSecret&&req.headers.get("x-cron-secret")===cronSecret;const user=await caller(req);const p=user?await profile(user.id):null;if(!isCron&&!p?.is_admin)return json({error:"forbidden"},403);if(body.mode==="announcement"&&body.announcement_id){const {data:a,error}=await admin.from("announcements").select("*").eq("id",body.announcement_id).single();if(error)return json({error:"announcement not found"},404);return json({ok:true,sent:await sendAnnouncement(a)})}const announcements=await processAnnouncements();const inactive=await processInactive();return json({ok:true,announcements_sent:announcements,inactive});}catch(e){console.error(e);return json({error:e instanceof Error?e.message:String(e)},500)}});
