import { createClient } from "npm:@supabase/supabase-js@2.57.4";
import { QUESTION_POOL, POOL_VERSION } from "./pool.ts";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,x-client-info,apikey,content-type,x-cron-secret","Access-Control-Allow-Methods":"POST,OPTIONS"};
const url=Deno.env.get("SUPABASE_URL")!;
const service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const anon=Deno.env.get("SUPABASE_ANON_KEY")!;
const cronSecret=Deno.env.get("CRON_SECRET")||"";
const admin=createClient(url,service,{auth:{persistSession:false}});
const answerMap=new Map<string,string>(QUESTION_POOL as any);
const poolIds=(QUESTION_POOL as any).map((x:any)=>x[0]) as string[];

function json(data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:{...cors,"Content-Type":"application/json"}})}
function kstDateKey(d=new Date()){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit"}).format(d)}
function weekStartKey(){const key=kstDateKey();const [y,m,d]=key.split("-").map(Number);const dt=new Date(Date.UTC(y,m-1,d,12));const dow=dt.getUTCDay()||7;dt.setUTCDate(dt.getUTCDate()-(dow-1));return `${dt.getUTCFullYear()}-${String(dt.getUTCMonth()+1).padStart(2,"0")}-${String(dt.getUTCDate()).padStart(2,"0")}`}
function addDays(k:string,n:number){const [y,m,d]=k.split("-").map(Number);const x=new Date(Date.UTC(y,m-1,d));x.setUTCDate(x.getUTCDate()+n);return `${x.getUTCFullYear()}-${String(x.getUTCMonth()+1).padStart(2,"0")}-${String(x.getUTCDate()).padStart(2,"0")}`}
function hashSeed(s:string){let h=2166136261>>>0;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed:number){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function choose50(week:string){const arr=[...poolIds];const r=rng(hashSeed(`${POOL_VERSION}:${week}`));for(let i=arr.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[arr[i],arr[j]]=[arr[j],arr[i]]}return arr.slice(0,50)}
async function caller(req:Request){const h=req.headers.get("Authorization")||"";if(!h.startsWith("Bearer "))return null;const client=createClient(url,anon,{global:{headers:{Authorization:h}},auth:{persistSession:false}});const {data}=await client.auth.getUser();return data.user||null}
async function approved(uid:string){const {data}=await admin.from("profiles").select("id,approval_status,is_admin").eq("id",uid).maybeSingle();return data?.approval_status==="approved"?data:null}
async function ensureRound(){const week=weekStartKey();let {data:round}=await admin.from("weekly_ranking_rounds").select("*").eq("week_start",week).maybeSingle();if(round)return round;const ids=choose50(week);const row={week_start:week,week_end:addDays(week,6),title:`${week} 주간랭킹전`,duration_minutes:50,question_count:50,question_ids:ids,pool_version:POOL_VERSION};const ins=await admin.from("weekly_ranking_rounds").insert(row).select("*").single();if(ins.error){const retry=await admin.from("weekly_ranking_rounds").select("*").eq("week_start",week).single();if(retry.error)throw ins.error;round=retry.data}else round=ins.data;return round}
function sanitizeAnswers(questionIds:string[],input:any){const out:Record<string,string>={};if(input&&typeof input==="object")for(const id of questionIds){const v=String(input[id]||"").toUpperCase();if(["A","B","C","D"].includes(v))out[id]=v}return out}
async function finalizeEntry(entry:any,round:any,incoming:any={},allowIncoming=true){const stored=sanitizeAnswers(round.question_ids,entry.answers||{});const extra=allowIncoming?sanitizeAnswers(round.question_ids,incoming||{}):{};const answers={...stored,...extra};let score=0;for(const id of round.question_ids)if(answers[id]&&answers[id]===answerMap.get(id))score++;const now=new Date();const started=new Date(entry.started_at);const duration=Math.min(round.duration_minutes*60,Math.max(0,Math.floor((now.getTime()-started.getTime())/1000)));const upd=await admin.from("weekly_ranking_entries").update({status:"submitted",submitted_at:now.toISOString(),score,duration_seconds:duration,answers,updated_at:now.toISOString()}).eq("id",entry.id).select("*").single();if(upd.error)throw upd.error;return upd.data}
async function finalizeExpired(){const rounds=await admin.from("weekly_ranking_rounds").select("*").gte("week_start",addDays(weekStartKey(),-14));if(rounds.error)throw rounds.error;let n=0;for(const round of rounds.data||[]){const cutoff=new Date(Date.now()-round.duration_minutes*60000).toISOString();const entries=await admin.from("weekly_ranking_entries").select("*").eq("round_id",round.id).eq("status","started").lt("started_at",cutoff);for(const e of entries.data||[]){await finalizeEntry(e,round,{},false);n++}}return n}

Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{const body=await req.json().catch(()=>({}));const mode=body.mode||"ensure";const isCron=cronSecret&&req.headers.get("x-cron-secret")===cronSecret;const user=await caller(req);const prof=user?await approved(user.id):null;
 if(mode==="maintenance"){if(!isCron&&!prof?.is_admin)return json({error:"forbidden"},403);const round=await ensureRound();const finalized=await finalizeExpired();return json({ok:true,round_id:round.id,week_start:round.week_start,finalized});}
 if(mode==="ensure"){if(!prof)return json({error:"approved members only"},403);const round=await ensureRound();const finalized=await finalizeExpired();return json({ok:true,round_id:round.id,week_start:round.week_start,finalized});}
 if(mode==="submit"){if(!prof)return json({error:"approved members only"},403);const roundId=String(body.round_id||"");const {data:round,error:rerr}=await admin.from("weekly_ranking_rounds").select("*").eq("id",roundId).single();if(rerr)return json({error:"round not found"},404);const {data:entry,error:eerr}=await admin.from("weekly_ranking_entries").select("*").eq("round_id",roundId).eq("user_id",user!.id).single();if(eerr)return json({error:"start the ranking round first"},409);if(entry.status==="submitted")return json({ok:true,score:entry.score,duration_seconds:entry.duration_seconds,already_submitted:true});const deadline=new Date(new Date(entry.started_at).getTime()+round.duration_minutes*60000);const allowIncoming=Date.now()<=deadline.getTime()+10000;const done=await finalizeEntry(entry,round,body.answers||{},allowIncoming);return json({ok:true,score:done.score,duration_seconds:done.duration_seconds,submitted_at:done.submitted_at,timed_out:!allowIncoming});}
 return json({error:"unsupported mode"},400);
}catch(e){console.error(e);return json({error:e instanceof Error?e.message:String(e)},500)}});
